# Generated by Django 5.2.12 on 2026-05-21 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(db_index=True, max_length=40, verbose_name='ID посетителя')),
                ('session_key', models.CharField(blank=True, max_length=80, verbose_name='Django session')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot'), ('unknown', 'Не определено')], default='unknown', max_length=24, verbose_name='Тип устройства')),
                ('device', models.CharField(blank=True, max_length=80, verbose_name='Устройство')),
                ('browser', models.CharField(blank=True, max_length=80, verbose_name='Браузер')),
                ('os', models.CharField(blank=True, max_length=80, verbose_name='ОС')),
                ('country_code', models.CharField(blank=True, max_length=8, verbose_name='Код страны')),
                ('country', models.CharField(blank=True, max_length=120, verbose_name='Страна')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Регион')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Город')),
                ('referrer', models.URLField(blank=True, max_length=800, verbose_name='Источник перехода')),
                ('referrer_domain', models.CharField(blank=True, max_length=220, verbose_name='Домен источника')),
                ('traffic_channel', models.CharField(choices=[('direct', 'Прямой заход'), ('internal', 'Внутренний переход'), ('organic_search', 'Поиск'), ('social', 'Соцсети'), ('paid', 'Реклама'), ('email', 'Email'), ('referral', 'Реферальный')], db_index=True, default='direct', max_length=32, verbose_name='Канал трафика')),
                ('utm_source', models.CharField(blank=True, max_length=160, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=160, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=220, verbose_name='UTM campaign')),
                ('utm_term', models.CharField(blank=True, max_length=220, verbose_name='UTM term')),
                ('utm_content', models.CharField(blank=True, max_length=220, verbose_name='UTM content')),
                ('landing_path', models.CharField(blank=True, max_length=600, verbose_name='Страница входа')),
                ('exit_path', models.CharField(blank=True, max_length=600, verbose_name='Последняя страница')),
                ('page_views_count', models.PositiveIntegerField(default=0, verbose_name='Просмотров за визит')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Начало визита')),
                ('last_seen_at', models.DateTimeField(db_index=True, verbose_name='Последняя активность')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_visits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Визит',
                'verbose_name_plural': 'Визиты',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WebPageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(db_index=True, max_length=600, verbose_name='Путь')),
                ('full_path', models.CharField(blank=True, max_length=1000, verbose_name='Полный путь')),
                ('referrer', models.URLField(blank=True, max_length=800, verbose_name='Источник перехода')),
                ('status_code', models.PositiveSmallIntegerField(default=200, verbose_name='HTTP статус')),
                ('viewport_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина viewport')),
                ('viewport_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота viewport')),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина экрана')),
                ('screen_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота экрана')),
                ('device_pixel_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='DPR')),
                ('language', models.CharField(blank=True, max_length=40, verbose_name='Язык браузера')),
                ('timezone', models.CharField(blank=True, max_length=80, verbose_name='Часовой пояс браузера')),
                ('color_scheme', models.CharField(blank=True, max_length=20, verbose_name='Цветовая схема')),
                ('connection_type', models.CharField(blank=True, max_length=40, verbose_name='Тип сети')),
                ('engagement_seconds', models.PositiveIntegerField(default=0, verbose_name='Время на странице, сек.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Просмотрена')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='web_page_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='webanalytics.webvisit', verbose_name='Визит')),
            ],
            options={
                'verbose_name': 'Просмотр страницы',
                'verbose_name_plural': 'Просмотры страниц',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webvisit',
            index=models.Index(fields=['visitor_id', 'last_seen_at'], name='webanalytic_visitor_ca44b6_idx'),
        ),
        migrations.AddIndex(
            model_name='webvisit',
            index=models.Index(fields=['country', 'city'], name='webanalytic_country_ac9717_idx'),
        ),
        migrations.AddIndex(
            model_name='webvisit',
            index=models.Index(fields=['device_type', 'browser'], name='webanalytic_device__53685e_idx'),
        ),
        migrations.AddIndex(
            model_name='webpageview',
            index=models.Index(fields=['path', 'created_at'], name='webanalytic_path_fcd0a1_idx'),
        ),
        migrations.AddIndex(
            model_name='webpageview',
            index=models.Index(fields=['created_at', 'status_code'], name='webanalytic_created_7c2b44_idx'),
        ),
    ]
