# Generated by Django 5.2.12 on 2026-05-22 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Основной адрес', max_length=120, verbose_name='Название')),
                ('recipient_name', models.CharField(blank=True, max_length=160, verbose_name='Получатель')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_addresses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Адрес доставки',
                'verbose_name_plural': 'Адреса доставки',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=160, verbose_name='Имя покупателя')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('customer_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('company', 'Юридическое лицо')], default='individual', max_length=24, verbose_name='Тип покупателя')),
                ('company_name', models.CharField(blank=True, max_length=220, verbose_name='Компания')),
                ('company_inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('company_kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('company_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('default_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customers.deliveryaddress', verbose_name='Адрес по умолчанию')),
            ],
            options={
                'verbose_name': 'Профиль покупателя',
                'verbose_name_plural': 'Профили покупателей',
            },
        ),
    ]
