# Generated by Django 5.2.12 on 2026-05-22 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Email подтвержден'),
        ),
        migrations.CreateModel(
            name='CustomerEmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('code_hash', models.CharField(max_length=128, verbose_name='Hash кода')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='Максимум попыток')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Подтвержден')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Код подтверждения email',
                'verbose_name_plural': 'Коды подтверждения email',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'email', 'verified_at'], name='customers_c_user_id_7a1914_idx'), models.Index(fields=['expires_at'], name='customers_c_expires_a6cf1c_idx')],
            },
        ),
    ]
