# Generated by Django 5.2.12 on 2026-05-22 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerprofile_email_verified_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailClientSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Включить отправку через эти настройки')),
                ('host', models.CharField(blank=True, max_length=255, verbose_name='SMTP host')),
                ('port', models.PositiveIntegerField(default=587, verbose_name='SMTP port')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='SMTP логин')),
                ('encrypted_password', models.TextField(blank=True, verbose_name='SMTP пароль')),
                ('from_email', models.CharField(blank=True, max_length=255, verbose_name='Email отправителя')),
                ('use_tls', models.BooleanField(default=True, verbose_name='TLS')),
                ('use_ssl', models.BooleanField(default=False, verbose_name='SSL')),
                ('timeout_seconds', models.PositiveIntegerField(default=15, verbose_name='Таймаут, сек.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Обновил')),
            ],
            options={
                'verbose_name': 'Настройки почтового клиента',
                'verbose_name_plural': 'Настройки почтового клиента',
            },
        ),
    ]
