# Generated by Django 5.2.12 on 2026-05-20 23:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='URL-ярлык')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('source_url', models.URLField(blank=True, verbose_name='Источник данных')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DoorProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=240, unique=True, verbose_name='URL-ярлык')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Артикул')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Цена')),
                ('width_min_mm', models.PositiveIntegerField(default=700, verbose_name='Мин. ширина, мм')),
                ('width_max_mm', models.PositiveIntegerField(default=1200, verbose_name='Макс. ширина, мм')),
                ('height_min_mm', models.PositiveIntegerField(default=2000, verbose_name='Мин. высота, мм')),
                ('height_max_mm', models.PositiveIntegerField(default=3000, verbose_name='Макс. высота, мм')),
                ('material', models.CharField(blank=True, max_length=120, verbose_name='Материал')),
                ('color', models.CharField(blank=True, max_length=120, verbose_name='Цвет профиля')),
                ('finish', models.CharField(blank=True, max_length=160, verbose_name='Отделка')),
                ('opening_type', models.CharField(choices=[('sliding', 'Раздвижная'), ('swing', 'Распашная'), ('hidden', 'Скрытая'), ('pivot', 'Pivot'), ('partition', 'Перегородка')], max_length=24, verbose_name='Тип открывания')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение')),
                ('image_url', models.URLField(blank=True, verbose_name='Внешнее изображение')),
                ('source_url', models.URLField(blank=True, verbose_name='Источник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Дверь',
                'verbose_name_plural': 'Двери',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='На складе')),
                ('reserved_quantity', models.PositiveIntegerField(default=0, verbose_name='В резерве')),
                ('min_quantity', models.PositiveIntegerField(default=1, verbose_name='Минимальный остаток')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.doorproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Остаток',
                'verbose_name_plural': 'Остатки',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('income', 'Поступление'), ('write_off', 'Списание'), ('reserve', 'Резерв'), ('release', 'Снятие резерва'), ('sale', 'Продажа'), ('adjustment', 'Корректировка')], max_length=24, verbose_name='Тип операции')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('reference', models.CharField(blank=True, max_length=160, verbose_name='Основание')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.doorproduct', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Движение склада',
                'verbose_name_plural': 'Движения склада',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='doorproduct',
            index=models.Index(fields=['is_active', 'opening_type'], name='catalog_doo_is_acti_e6d32a_idx'),
        ),
        migrations.AddIndex(
            model_name='doorproduct',
            index=models.Index(fields=['price'], name='catalog_doo_price_c534ac_idx'),
        ),
    ]
