# Generated by Django 5.2.12 on 2026-05-21 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_public_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('can_confirm_order', 'Может подтверждать заказы и списывать склад'), ('can_export_order_docs', 'Может выгружать документы по заказам'), ('can_simulate_payment', 'Может проводить имитацию оплаты')], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='company_address',
            field=models.TextField(blank=True, verbose_name='Юридический адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_inn',
            field=models.CharField(blank=True, max_length=12, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_kpp',
            field=models.CharField(blank=True, max_length=9, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=220, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('company', 'Юридическое лицо')], default='individual', max_length=24, verbose_name='Тип покупателя'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к оплате'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Банковская карта'), ('sbp', 'СБП'), ('bank_transfer', 'Безналичный перевод'), ('cash_on_delivery', 'Оплата при получении')], default='card', max_length=32, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=64, verbose_name='Номер платежа'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('waiting', 'Ожидает оплаты'), ('processing', 'В обработке'), ('paid', 'Оплачен'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возврат')], default='waiting', max_length=24, verbose_name='Статус оплаты'),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('method', models.CharField(choices=[('card', 'Банковская карта'), ('sbp', 'СБП'), ('bank_transfer', 'Безналичный перевод'), ('cash_on_delivery', 'Оплата при получении')], max_length=32, verbose_name='Способ оплаты')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('succeeded', 'Успешен'), ('failed', 'Отклонен'), ('refunded', 'Возврат')], default='created', max_length=24, verbose_name='Статус')),
                ('provider', models.CharField(default='DoorSky Pay Simulator', max_length=80, verbose_name='Провайдер')),
                ('reference', models.CharField(max_length=64, unique=True, verbose_name='Номер операции')),
                ('error_message', models.CharField(blank=True, max_length=240, verbose_name='Ошибка')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Технические данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Обработана')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платежная операция',
                'verbose_name_plural': 'Платежные операции',
                'ordering': ['-created_at'],
            },
        ),
    ]
